openapi: 3.0.0
servers:
  - url: https://www.taxpower.com/api/v1
    description: production server
info:
  description: |
    # Introduction
     This document explains how to communicate with the TaxPower API.

     | **Go to another page**                                                                                   |
     |----------------------------------------------------------------------------------------------------------|
     | [TaxPower API Documentation](https://ingrey1.github.io/taxpower/docs/overview/)                          |
     | [Learn To Use This API Reference](https://ingrey1.github.io/taxpower/docs/getting-started/account-setup) |

     | **Requirements Before Making Request** |
     |---------------------------------------------------------------------------------------------------------------------|
     | [Signup For An Account](https://ingrey1.github.io/taxpower/docs/getting-started/account-setup)                      |
     | [Generate An API Key](https://ingrey1.github.io/taxpower/docs/getting-started/generate-api-key)                     |


    # Authentication
     <SecurityDefinitions />
  version: 1.0.0
  title: TaxPower API
x-tagGroups:
  - name: Tax Management
    tags:
      - Tax
paths:
  /tax/calculate:
    parameters:
      - name: accept
        in: header
        description: The response data will be in JSON format.
        required: true
        schema:
          type: string
          default: application/json
      - name: api_key
        in: header
        description: Used to authenticate the request.
        required: true
        example: apikey1234abcdefghij0123456789
        schema:
          type: string
      - name: amount
        in: query
        description: This is the base amount that will be used to calculate the tax.
        required: true
        example: 19.99
        schema:
          type: number
      - name: zipcode
        in: query
        description: >-
          The tax rate used to calculate the tax will be retrieved using this
          zipcode.
        required: true
        example: 95501
        schema:
          type: number
      - name: currency
        in: query
        description: The desired currency you want the TaxPower API to respond with.
        required: false
        example: USD
        schema:
          type: string
          enum:
            - USD
            - EUR
          default: USD
    get:
      summary: Calculate Tax
      description: Calculate tax for any zipcode in the US. Multiple currencies supported.
      operationId: Calculate Tax
      tags:
        - Tax
      security:
        - api_key: []
      responses:
        '200':
          description: Successful Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaxSuccess'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tax400'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tax500'
components:
  schemas:
    Tax400:
      type: object
      properties:
        statusCode:
          type: integer
          description: HTTP code for response status
          example: 400
        error:
          type: object
          properties:
            name:
              type: string
              example: Bad Request
            reason:
              type: string
              example: Invalid API key
    Tax500:
      type: object
      properties:
        statusCode:
          type: integer
          description: HTTP code for response status
          example: 500
        error:
          type: object
          properties:
            name:
              type: string
              example: Internal Server Error
            reason:
              type: string
              example: The TaxPower service could not be reached. Try again later.
    TaxSuccess:
      type: object
      properties:
        statusCode:
          type: integer
          description: HTTP code for response status
          example: 200
        data:
          type: object
          properties:
            zipcode:
              type: number
              example: 95501
            currency:
              type: string
              example: USD
            baseAmount:
              type: number
              example: 100
            taxRate:
              type: number
              example: 0.1
            tax:
              type: number
              example: 10
            totalAmount:
              type: number
              example: 110
  securitySchemes:
    api_key:
      description: >
        Attach your valid API key as the value for the "api_key" header to make
        authenticated requests.   
      type: apiKey
      name: api_key
      in: header
